version: 2.1
executors:
  default:
    working_directory: /go/src/github.com/cpanato/mattermost-plugin-chucknorris-facts
    docker:
      - image: circleci/golang:1.12

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: make check-style

  build:
    executor:
      name: default
    steps:
      - checkout
      - run: make dist
      - persist_to_workspace:
          root: .
          paths: ./dist/*.tar.gz

  publish-github-release:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./dist/com.cpanato.chucknorris-facts-*.tar.gz

workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
  tagged-build:
    jobs:
      - lint:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - lint
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-github-release:
          context: cpanato-gh-token
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
