name: BuildChecks
on:
  push:
    branches:
    - master
    tags:
    - /^v.*/
  pull_request:

jobs:
  build:
    name: BuildCheck
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - uses: actions/checkout@v1

    - name: Check Style
      run: make check-style

    - name: Coverage
      run: make coverage

    - name: Upload Coverage
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: server/coverage.txt

    - name: Build
      run: make dist
      
    - uses: actions/upload-artifact@master
      with:
        name: com.cpanato.chucknorris-facts-${{ github.event.ref }}.tar.gz
        path: dist/com.cpanato.chucknorris-facts-${{ github.event.ref }}.tar.gz
